# Use an official ROS 2 Humble base image with CUDA support
FROM nvidia/cuda:11.7.1-base-ubuntu20.04

ENV DEBIAN_FRONTEND=noninteractive

# Install ROS 2 Humble
RUN apt-get update && apt-get install -y \
    add-apt-repository universe \
    locales \
    curl \
    gnupg \
    wget \
    sudo \
    software-properties-common \
    lsb-release && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2-latest.list && \
    apt-get update && apt-get install -y \
    ros-foxy-desktop \
    python3-pip \
    python3-colcon-common-extensions \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Install NVIDIA OpenGL libraries for GPU GUI support
RUN apt-get update && apt-get install -y \
    libglvnd-dev \
    libgl1-mesa-glx \
    libegl1-mesa \
    libxrandr2 \
    libxinerama1 \
    libxcursor1 \
    libxcomposite1 \
    libasound2 \
    libxi6 \
    libxtst6 \
    && rm -rf /var/lib/apt/lists/*

# sudo apt-get update
# sudo apt-get install curl lsb-release gnupg
# sudo curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg
# echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null
# sudo apt-get update
# sudo apt-get install gz-harmonic

# Set up ROS 2 environment
RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
SHELL ["/bin/bash", "-c"]

# Create a workspace
RUN mkdir -p /root/ros2_ws/src
WORKDIR /root/ros2_ws

# Default command
CMD ["bash"]
